name: Chocolatine Workflow

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: 'https://github.com/mrd-titouan/B-DOP-200-chocolatine'
  EXECUTABLES: 'pushswap,lib/my/libmy.a,antman/antman,giantman/giantman'

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    